### ISSUE TITLE
suppress auto-numbering of captions

### ISSUE THREAD

**Issue by januz** [nutterb/pixiedust#108]
is there a way to have captions printed as-is, i.e., without the "Table #:" prefix?

**Comment by nutterb** [comment]
You can use `devtools::install_github("nutterb/pixiedust", ref = "devel")` for now.  I just added this feature with the `caption_number` sprinkle.  Setting `caption_number = FALSE` in either `dust`, or `sprinkle` should do the trick.

I want to get this (and other) features to CRAN soon, but I'm going to have to sort out some Reverse Dependency issues first.
