### ISSUE TITLE
sprinkle_table(width=) no longer working

### ISSUE THREAD

**Issue by kgottstine** [nutterb/pixiedust#113]
I recently updated to v 8.2 and had previously been using code that used sprinkle_table(width = ) that worked perfectly, but once I updated it no longer honors the widths I set.

I haven't been able to find if this was impacted by the update, or why it is no longer working!

**Comment by nutterb** [comment]
I'm pretty sure this is related to the update. I will look at it this week and try to resolve it.

**Comment by nutterb** [comment]
Looking at this again, it's clear that I did break the backward compatibility.  I'm not sure this was such a bad thing in this case, as it requires some thought about how to recycle multiple values over the row/column dimensions.

I would recommend using something like the following:

```r
library(pixiedust)

dust(lm(mpg ~ qsec + wt + am,
        data = mtcars)) %>% 
  medley_bw() %>% 
  sprinkle_table(cols = c("statistic", "p.value"),
                 width = c(2, 4),
                 width_units = "in",
                 recycle = "rows")
```

This should get your desired behavior for now.

I'm going to open a new issue to bring myself back to considering if recycling should be assumed when the number of columns matches the number of inputs.
