### ISSUE TITLE
Printing `NA` values

### ISSUE THREAD

**Issue by renlund** [nutterb/pixiedust#21]
Would it be possible to add some option to `print.dust` so that `NA` values can be printed as blanks?

Thanks for a very nice R package.

**Comment by nutterb** [comment]
I think that's a useful and workable addition.  I think I'd prefer to put the argument in `dust` and `sprinkle_table`; that way it would take effect even under implicit prints.

Would you be satisfied with an additional argument `na_string = ""` to both of those functions?

**Comment by renlund** [comment]
Yes, that would be excellent.

**Comment by nutterb** [comment]
Great.  This should appear on GitHub by the end of the month and hit CRAN in the mid-October release.

**Comment by renlund** [comment]
Thanks!

**Comment by nutterb** [comment]
This is implemented in the development branch. It will get pushed up to the master branch when I resolve an unrelated bug.
