### ISSUE TITLE
Row names not captured

### ISSUE THREAD

**Issue by notdeadjustslob** [nutterb/pixiedust#23]
Hi, 

Is there a way to capture the row names from a table using dust?
I know I could just save the bit I want as a dataframe and then cbind the row names and df and then run dust on that but I was trying to avoid extraneous code. Maybe I am missing an option?

Thanks for a much needed package.

**Comment by nutterb** [comment]
This is fairly straightforward to implement.  There's more documentation involved than anything else.  I'll work this in between versions 0.3.0 and 0.4.0.  It should be available on GitHub by the end of the month and on CRAN around mid-October.

**Comment by nutterb** [comment]
This is implemented in the development branch.  It will get pushed up to the master branch when I resolve an unrelated bug.
