### ISSUE TITLE
Add a Title

### ISSUE THREAD

**Issue by iantist** [nutterb/pixiedust#41]
Is it possible to add a title?

**Comment by nutterb** [comment]
Not yet, unfortunately. I haven't decided how to approach this for HTML tables yet.

I have some work to do on another project, but table titles/captions are at the top of the list for when I get back to pixiedust.

**Comment by iantist** [comment]
Great, thanks for your hard work! I am really enjoying using the package.

**Comment by nutterb** [comment]
Added to 6.0.1, currently in the `new-latex-tables` branch.
