### ISSUE TITLE
reducing white space after html tables

### ISSUE THREAD

**Issue by nutterb** [nutterb/pixiedust#57]
I have a couple of `<br/>` tags at the end of the HTML tables.  I need to see if these are strictly necessary or if they could be optionally removed.

**Comment by kgottstine** [comment]
I am running into issues with the white space after html tables, I have been trying to use `***` to produce a horizontal line after a table to split up my html report but depending on the number of rows the pixiedust table has, the line either does not show up or shows up behind the middle of the table. I am using the code for the table in a script that will be used to generate many reports and need a fix that will not require manually changing the margin on the bottom of the table, or adding several <br/> tags at the end of the table to get the desired result. 

`*** ` works in other portions of my report, after graphs, after chunks of text, I just can't get it to work after the table.

**Comment by nutterb** [comment]
Without a reproducible example, it's hard to give you specific advice.  I can say that there is an argument in the print method that specifies how many linebreaks to put at the end of the table.  Compare the output below:

    ---
    title: "Untitled"
    output: html_document
    ---

    ```{r}
    library(pixiedust)

    knitr::opts_chunk$set(echo = FALSE)

    mtcars %>%
      dust() %>%
      medley_bw() 
    ```

    ***

    ```{r}
    mtcars %>%
      dust() %>%
      medley_bw() %>%
      print(linebreak_at_end = 1)
    ```

    ***
    
    ```{r}
    mtcars %>%
      dust() %>%
      medley_bw() %>%
      print(linebreak_at_end = 10)
    ```
    
    ***

As I look at this now, I realize that this argument really ought to reference an option so that it can be set globally.

**Comment by kgottstine** [comment]
Following is my code to produce the table (you had actually helped me with another issue the other day regarding this table)

```
```{r SD and Mean Table, echo = FALSE, results = 'asis', warning = FALSE}  
line.table[line.cols] %>%   
  dust(justify = "left") %>%  
  medley_all_borders(part = "table") %>%  
  sprinkle_table(halign = "left", pad = 2.5) %>%  
  sprinkle(rows = which(line.table$`Mean Pass/Fail` == "Fail"), col = "Mean Pass/Fail", 
           bg = "rgba(255, 00, 00, .7)") %>%  
  sprinkle(rows = which(line.table$`Mean Pass/Fail` == "Pass"), col = "Mean Pass/Fail", 
           bg = "rgba(63, 255, 00, .7)") %>%   
  print(asis = FALSE, linebreak_at_end = 1) %>% cat()
```
```
***
### Plots
```

Note: the horizontal line follows the end of the chunk.

When I have 2 lines in the table, I get the following output in the html file

![capture](https://user-images.githubusercontent.com/29205815/26932397-5d08175e-4c31-11e7-8af2-7d5f8222bb17.PNG)

Then when I have 20 rows, I get the following output in the html file

![capture2](https://user-images.githubusercontent.com/29205815/26932430-7bcc129e-4c31-11e7-9e3e-7e6eb84aaf95.PNG)

**Comment by nutterb** [comment]
I just learned something new!  The problem is the `justify = "left"`.  The solution appears to be using `justify = "")`.  By default, everything is left aligned in HTML, and using `justify = "left"` sets the table as a kind of float (? but not really?) and messes with all sorts of settings.  I'll file another issue to have `justify = "left"` omit the alignment option from that table so that it behaves properly in the future.

For now, this seems to work.

    ---
    title: "Untitled"
    output: html_document
    ---
    ```{r SD and Mean Table, echo = FALSE, results = 'asis', warning = FALSE}  
    library(pixiedust)
    mtcars %>%   
      dust(justify = "") %>%  
      medley_all_borders(part = "table") %>%  
      sprinkle_table(halign = "left", pad = 2.5) %>%  
      sprinkle(rows = which(mtcars$gear == 4), 
               col = "mpg", 
               bg = "rgba(255, 00, 00, .7)") %>%  
      sprinkle(rows = which(mtcars$gear == 3), 
               col = "mpg", 
               bg = "rgba(63, 255, 00, .7)") %>%   
      print(asis = FALSE, linebreak_at_end = 0) %>%
      cat()
    ```

    ***
    ### Plots

**Comment by kgottstine** [comment]
Thank you very much! I really enjoy using your package, it's made it very easy to customize tables that my company needs to use. We appreciate your quick responses to questions!

**Comment by nutterb** [comment]
I'm working on this right now, and in `pixiedust` 0.8, I am going to restrict the options for `justify` to "center", "none", "left", and "right".  This means the code I've given above will break.

Where I have `dust(justify = "")` will need to be `dust(justify = "none")`.

It still works in the current base to use `dust(justify = "none")`, so I would recommend making that change now so that you're not surprised when 0.8 comes out later this summer.
