### ISSUE TITLE
Default Sprinkle Set?

### ISSUE THREAD

**Issue by ckraner** [nutterb/pixiedust#79]
I'm very sorry if this is somewhere, but I thought I read you can make a default set of sprinkles? If not....this would be very very helpful.

**Comment by ckraner** [comment]
Nevermind...called Medley

**Comment by ckraner** [comment]
How do you create your own Medleys?

**Comment by ckraner** [comment]
So I need to repackage pixiedust in order to make my own medleys?

**Comment by nutterb** [comment]
You are correct that this isn't given much discussion in the documentation.  It seems you may have already found your solution, but just in case, they medleys are really only a function.  For example, if I always want `pad = 3` and striped rows, I can define

```r
some_medley <- function(x){
  x %>%
    sprinkle(pad = 3,
                  bg_pattern_by = "rows")
}
```

These can run as complex or simplistic as needed.  

I will be adding more long form documentation about `pixiedust` which will have a chapter devoted to medleys.  It's still under development, and I haven't yet written that chapter. (http://nutterb.github.io/pixiedust/index.html)
