### ISSUE TITLE
Removing additional line breaks between caption and table latex?

### ISSUE THREAD

**Issue by HelenaEdlund** [nutterb/pixiedust#90]
When I print the table to latex I get a large space between the caption and the table. It looks like it is printing additional \\ after both the caption and the label statements:
\\begin{longtable}[c]{llrl}\n
\\caption{ My caption }\\\\\n
\\label{tab:myLabel}\\\\ \n 
\\hhline ... 
Is there some functionality to remove that? 
Thanks!

**Comment by nutterb** [comment]
Thank for noticing this.  Please use `install_github("nutterb/pixiedust")` to download the patched version (0.7.5-2)

**Comment by HelenaEdlund** [comment]
Great, thanks!
