### ISSUE TITLE
Error producing PDF with pixiedust table

### ISSUE THREAD

**Issue by kgottstine** [nutterb/pixiedust#93]
I am trying to use the pixiedust package to create tables in my PDF output report. I wasn't sure what packages needed to be included in the heading, so I'm currently using an example I saw online: 

```
output: pdf_document
header-includes:
- \usepackage{amssymb} 
- \usepackage{arydshln} 
- \usepackage{caption} 
- \usepackage{graphicx} 
- \usepackage{hhline} 
- \usepackage{longtable} 
- \usepackage{multirow} 
- \usepackage[dvipsnames,table]{xcolor}
```

The table I'm trying to output is simple without any extra sprinkles at the moment:

```
{r, echo = FALSE}
options(pixiedust_print_method = "latex")
Min <- 20
Max <- 625
Test <- 6
Predicate <- 1

ORR.summary <- cbind(Min, Max, Test, Predicate)

dust(ORR.summary)

```

Then I get the following error message when trying to knit the PDF: 

! Missing number, treated as zero.
<to be read again> 
                   I
l.99 ...-Infpt}{\raggedleft Reportable.Range.Min}}

pandoc.exe: Error producing PDF
Error: pandoc document conversion failed with error 43
In addition: Warning message:
running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS ORR_Table.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output ORR_Table.pdf --template "C:\Users\kgottsti\Documents\R\win-library\3.4\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in"' had status 43 
Execution halted

I have tried searching for solutions online but can't seem to find anything to help.

**Comment by nutterb** [comment]
This was identified with Issue #82 and was fixed in PR #83.  This fix hasn't yet made it to CRAN (I happen to be working on that right now).  If you download the development version, everything should work well `devtools::install_github("nutterb/pixiedust")`.

Please report back if the problem persists.
